/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface About {
  'bio' : string,
  'clientsCount' : bigint,
  'yearsExperience' : bigint,
  'projectsCount' : bigint,
}
export type Category = { 'DataScience' : null } |
  { 'Frontend' : null } |
  { 'DevOps' : null } |
  { 'Backend' : null };
export type Category__1 = { 'Frontend' : null } |
  { 'FullStack' : null } |
  { 'Backend' : null } |
  { 'Mobile' : null };
export interface Contact {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Experience {
  'endDate' : [] | [Time],
  'role' : string,
  'description' : string,
  'company' : string,
  'isCurrent' : boolean,
  'startDate' : Time,
}
export interface Project {
  'title' : string,
  'description' : string,
  'githubUrl' : string,
  'imageUrl' : string,
  'category' : Category__1,
  'liveUrl' : string,
  'techStack' : Array<Tech>,
}
export interface Skill {
  'name' : string,
  'proficiency' : bigint,
  'category' : Category,
}
export interface Tech { 'name' : string }
export type Time = bigint;
export interface _SERVICE {
  'addExperience' : ActorMethod<
    [string, string, Time, [] | [Time], string, boolean],
    undefined
  >,
  'addProject' : ActorMethod<
    [string, string, Array<Tech>, string, string, Category__1, string],
    undefined
  >,
  'addSkill' : ActorMethod<[string, Category, bigint], undefined>,
  'getAbout' : ActorMethod<[], About>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getExperience' : ActorMethod<[], Array<Experience>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getSkills' : ActorMethod<[], Array<Skill>>,
  'removeExperience' : ActorMethod<[string], undefined>,
  'removeProject' : ActorMethod<[string], undefined>,
  'removeSkill' : ActorMethod<[string], undefined>,
  'submitContact' : ActorMethod<[string, string, string, string], undefined>,
  'updateAbout' : ActorMethod<[string, bigint, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];