/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Tech = IDL.Record({ 'name' : IDL.Text });
export const Category__1 = IDL.Variant({
  'Frontend' : IDL.Null,
  'FullStack' : IDL.Null,
  'Backend' : IDL.Null,
  'Mobile' : IDL.Null,
});
export const Category = IDL.Variant({
  'DataScience' : IDL.Null,
  'Frontend' : IDL.Null,
  'DevOps' : IDL.Null,
  'Backend' : IDL.Null,
});
export const About = IDL.Record({
  'bio' : IDL.Text,
  'clientsCount' : IDL.Nat,
  'yearsExperience' : IDL.Nat,
  'projectsCount' : IDL.Nat,
});
export const Contact = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Experience = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'role' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'isCurrent' : IDL.Bool,
  'startDate' : Time,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'githubUrl' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category__1,
  'liveUrl' : IDL.Text,
  'techStack' : IDL.Vec(Tech),
});
export const Skill = IDL.Record({
  'name' : IDL.Text,
  'proficiency' : IDL.Nat,
  'category' : Category,
});

export const idlService = IDL.Service({
  'addExperience' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Opt(Time), IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'addProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(Tech),
        IDL.Text,
        IDL.Text,
        Category__1,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addSkill' : IDL.Func([IDL.Text, Category, IDL.Nat], [], []),
  'getAbout' : IDL.Func([], [About], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getExperience' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'removeExperience' : IDL.Func([IDL.Text], [], []),
  'removeProject' : IDL.Func([IDL.Text], [], []),
  'removeSkill' : IDL.Func([IDL.Text], [], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateAbout' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Tech = IDL.Record({ 'name' : IDL.Text });
  const Category__1 = IDL.Variant({
    'Frontend' : IDL.Null,
    'FullStack' : IDL.Null,
    'Backend' : IDL.Null,
    'Mobile' : IDL.Null,
  });
  const Category = IDL.Variant({
    'DataScience' : IDL.Null,
    'Frontend' : IDL.Null,
    'DevOps' : IDL.Null,
    'Backend' : IDL.Null,
  });
  const About = IDL.Record({
    'bio' : IDL.Text,
    'clientsCount' : IDL.Nat,
    'yearsExperience' : IDL.Nat,
    'projectsCount' : IDL.Nat,
  });
  const Contact = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Experience = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'role' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'isCurrent' : IDL.Bool,
    'startDate' : Time,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'githubUrl' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category__1,
    'liveUrl' : IDL.Text,
    'techStack' : IDL.Vec(Tech),
  });
  const Skill = IDL.Record({
    'name' : IDL.Text,
    'proficiency' : IDL.Nat,
    'category' : Category,
  });
  
  return IDL.Service({
    'addExperience' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Opt(Time), IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'addProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(Tech),
          IDL.Text,
          IDL.Text,
          Category__1,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addSkill' : IDL.Func([IDL.Text, Category, IDL.Nat], [], []),
    'getAbout' : IDL.Func([], [About], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getExperience' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'removeExperience' : IDL.Func([IDL.Text], [], []),
    'removeProject' : IDL.Func([IDL.Text], [], []),
    'removeSkill' : IDL.Func([IDL.Text], [], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateAbout' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };