/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Contact {
    subject: string;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface Tech {
    name: string;
}
export interface Skill {
    name: string;
    proficiency: bigint;
    category: Category;
}
export interface Experience {
    endDate?: Time;
    role: string;
    description: string;
    company: string;
    isCurrent: boolean;
    startDate: Time;
}
export interface About {
    bio: string;
    clientsCount: bigint;
    yearsExperience: bigint;
    projectsCount: bigint;
}
export interface Project {
    title: string;
    description: string;
    githubUrl: string;
    imageUrl: string;
    category: Category__1;
    liveUrl: string;
    techStack: Array<Tech>;
}
export enum Category {
    DataScience = "DataScience",
    Frontend = "Frontend",
    DevOps = "DevOps",
    Backend = "Backend"
}
export enum Category__1 {
    Frontend = "Frontend",
    FullStack = "FullStack",
    Backend = "Backend",
    Mobile = "Mobile"
}
export interface backendInterface {
    addExperience(role: string, company: string, startDate: Time, endDate: Time | null, description: string, isCurrent: boolean): Promise<void>;
    addProject(title: string, description: string, techStack: Array<Tech>, liveUrl: string, githubUrl: string, category: Category__1, imageUrl: string): Promise<void>;
    addSkill(name: string, category: Category, proficiency: bigint): Promise<void>;
    getAbout(): Promise<About>;
    getAllContacts(): Promise<Array<Contact>>;
    getExperience(): Promise<Array<Experience>>;
    getProjects(): Promise<Array<Project>>;
    getSkills(): Promise<Array<Skill>>;
    removeExperience(role: string): Promise<void>;
    removeProject(title: string): Promise<void>;
    removeSkill(name: string): Promise<void>;
    submitContact(name: string, email: string, subject: string, message: string): Promise<void>;
    updateAbout(bio: string, yearsExperience: bigint, projectsCount: bigint, clientsCount: bigint): Promise<void>;
}
import type { Category as _Category, Category__1 as _Category__1, Experience as _Experience, Project as _Project, Skill as _Skill, Tech as _Tech, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExperience(arg0: string, arg1: string, arg2: Time, arg3: Time | null, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExperience(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExperience(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async addProject(arg0: string, arg1: string, arg2: Array<Tech>, arg3: string, arg4: string, arg5: Category__1, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(arg0, arg1, arg2, arg3, arg4, to_candid_Category__1_n2(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(arg0, arg1, arg2, arg3, arg4, to_candid_Category__1_n2(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async addSkill(arg0: string, arg1: Category, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSkill(arg0, to_candid_Category_n4(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSkill(arg0, to_candid_Category_n4(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async getAbout(): Promise<About> {
        if (this.processError) {
            try {
                const result = await this.actor.getAbout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAbout();
            return result;
        }
    }
    async getAllContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContacts();
            return result;
        }
    }
    async getExperience(): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExperience();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExperience();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSkills(): Promise<Array<Skill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkills();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkills();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeExperience(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeExperience(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeExperience(arg0);
            return result;
        }
    }
    async removeProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProject(arg0);
            return result;
        }
    }
    async removeSkill(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSkill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSkill(arg0);
            return result;
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateAbout(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAbout(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAbout(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Category__1_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category__1): Category__1 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Experience_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Experience): Experience {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Skill_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Skill): Skill {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    githubUrl: string;
    imageUrl: string;
    category: _Category__1;
    liveUrl: string;
    techStack: Array<_Tech>;
}): {
    title: string;
    description: string;
    githubUrl: string;
    imageUrl: string;
    category: Category__1;
    liveUrl: string;
    techStack: Array<Tech>;
} {
    return {
        title: value.title,
        description: value.description,
        githubUrl: value.githubUrl,
        imageUrl: value.imageUrl,
        category: from_candid_Category__1_n13(_uploadFile, _downloadFile, value.category),
        liveUrl: value.liveUrl,
        techStack: value.techStack
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    proficiency: bigint;
    category: _Category;
}): {
    name: string;
    proficiency: bigint;
    category: Category;
} {
    return {
        name: value.name,
        proficiency: value.proficiency,
        category: from_candid_Category_n18(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate: [] | [_Time];
    role: string;
    description: string;
    company: string;
    isCurrent: boolean;
    startDate: _Time;
}): {
    endDate?: Time;
    role: string;
    description: string;
    company: string;
    isCurrent: boolean;
    startDate: Time;
} {
    return {
        endDate: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.endDate)),
        role: value.role,
        description: value.description,
        company: value.company,
        isCurrent: value.isCurrent,
        startDate: value.startDate
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Frontend: null;
} | {
    FullStack: null;
} | {
    Backend: null;
} | {
    Mobile: null;
}): Category__1 {
    return "Frontend" in value ? Category__1.Frontend : "FullStack" in value ? Category__1.FullStack : "Backend" in value ? Category__1.Backend : "Mobile" in value ? Category__1.Mobile : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    DataScience: null;
} | {
    Frontend: null;
} | {
    DevOps: null;
} | {
    Backend: null;
}): Category {
    return "DataScience" in value ? Category.DataScience : "Frontend" in value ? Category.Frontend : "DevOps" in value ? Category.DevOps : "Backend" in value ? Category.Backend : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Skill>): Array<Skill> {
    return value.map((x)=>from_candid_Skill_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Experience>): Array<Experience> {
    return value.map((x)=>from_candid_Experience_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Category__1_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category__1): _Category__1 {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category__1): {
    Frontend: null;
} | {
    FullStack: null;
} | {
    Backend: null;
} | {
    Mobile: null;
} {
    return value == Category__1.Frontend ? {
        Frontend: null
    } : value == Category__1.FullStack ? {
        FullStack: null
    } : value == Category__1.Backend ? {
        Backend: null
    } : value == Category__1.Mobile ? {
        Mobile: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    DataScience: null;
} | {
    Frontend: null;
} | {
    DevOps: null;
} | {
    Backend: null;
} {
    return value == Category.DataScience ? {
        DataScience: null
    } : value == Category.Frontend ? {
        Frontend: null
    } : value == Category.DevOps ? {
        DevOps: null
    } : value == Category.Backend ? {
        Backend: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
